name: habit_tracker
description: "A habit tracking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  flutter_typeahead: ^4.0.0
  firebase_ml_model_downloader: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Since we're using Google Fonts, we don't need to specify font assets here
  # as they will be downloaded and cached at runtime
